import = [
    "~/.config/alacritty/themes/themes/breeze.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 11.0

[font.normal]
family = "FiraCodeNerdFont"
style = "Regular"

[window]
padding.x = 4
padding.y = 4
dynamic_padding = true

dimensions = { columns = 94, lines = 24}

opacity = 0.75
blur = true
